// FE/huey/src/components/main/Rooms.vue
<template>
  <div class="rooms-wrap">
    <h2 class="rooms-title"></h2>
    <RoomLists />
  </div>
</template>

<script>
import RoomLists from '@/components/main/RoomLists';

export default {
  data() {
    return {};
  },
  created() {
    this.$store.dispatch('INIT_RENDER');
  },
  components: {
    RoomLists,
  },
  methods: {},
};
</script>

<style lang="scss" scoped>
.rooms-wrap {
  margin-top: 60px;
}

.rooms-title {
  font-size: 20px;
  font-weight: 600;
  color: #000;
}
</style>

// FE/TAEK/src/components/main/rooms/Rooms.jsx
import React from 'react'
import styled from 'styled-components';
import RoomList from './RoomList';

import { roomsData } from 'mock/mockData';

const RoomsWrap = styled.div`
    margin-top: 60px;
`;

const RoomsTitle = styled.h2`
    font-size: 20px;
    font-weight: 600;
    color: #000;
`;

const Rooms = () => {
    const { allData } = roomsData;

    return (
        <RoomsWrap>
            <RoomsTitle>{allData.length}개 이상의 숙소</RoomsTitle>
            <RoomList {...{ allData }} />
        </RoomsWrap>
    )
}

export default Rooms
